# permissions for end users to edit fights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fight-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubemon
    app.kubernetes.io/part-of: kubemon
    app.kubernetes.io/managed-by: kustomize
  name: fight-editor-role
rules:
- apiGroups:
  - kubemon.memetoasty.github.com
  resources:
  - fights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemon.memetoasty.github.com
  resources:
  - fights/status
  verbs:
  - get
