---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubemon.memetoasty.github.com
  resources:
  - kubemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubemon.memetoasty.github.com
  resources:
  - kubemons/finalizers
  verbs:
  - update
- apiGroups:
  - kubemon.memetoasty.github.com
  resources:
  - kubemons/status
  verbs:
  - get
  - patch
  - update
